---
# Task file for CIS Controls
# This file is commented to help view what Ansible Automation is doing
#  and under what circumstances.

# Some blocks below have tasks with tags and some without. Blocks of tasks that
#  contain multiple controls have tasks with tags. Blocks that consist of a
#  single control and are just put together for convenience sake, do not have
#  sub-block tasks with tags.

# Comments about how the modules are used will become more infrequent as
#  the file goes along to avoid repeating oneself.

# Let the user know what version of the controls file is running
# Use a variable so it prints out the correct version.
- name: Print Header
  ansible.builtin.debug:
    msg: "CIS Controls for {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

# Collect the packages installed on the system so we can check agains them later
- name: Collect package list
  ansible.builtin.package_facts:
    manager: auto
  tags:
    - always

# Update the system with security packages using the system's package manager
#  Only update the system if the 'update_system' variable is set to true
- name: 1.9.0 - Ensure updated system
  community.general.pkgng:
    name: "*"
    state: latest
  when: update_system
  tags:
    - 1.9.0

- name: 1.1.1 - Configure Filesystem Kernel Modules
  tags:
    - 1.1.1
  block:
    - name: 1.1.1.1 - Ensure ext2fs kernel module is not available
      when: disable_ext2fs | default(true)
      community.general.sysrc:
        name: "ext2fs_load"
        state: present
        value: "NO"
        path: /boot/loader.conf
      tags:
        - 1.1.1.1

    - name: 1.1.1.2 - Ensure msdosfs kernel module is not available
      when: disable_msdosfs | default(true)
      community.general.sysrc:
        name: "msdosfs_load"
        state: present
        value: "NO"
        path: /boot/loader.conf
      tags:
        - 1.1.1.2

    - name: 1.1.1.3 - Ensure zfs kernel module is not available
      when: disable_zfs | default(true)
      block:
        - name: 1.1.1.3 - disable zfs kernel module
          community.general.sysrc:
            name: "zfs_load"
            state: present
            value: "NO"
            path: /boot/loader.conf

        - name: 1.1.1.3 - disable zfs services
          community.general.sysrc:
            name: "zfs_enable"
            state: present
            value: "NO"
      tags:
        - 1.1.1.3

- name: 1.1.2 - Configure Filesystem Partitions
  tags:
    - 1.1.2
  include_tasks: freebsd-fs.yml
  loop: "{{ cis_freebsd_filesystems | default([]) }}"
